             /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hms.login;

import com.hms.gui.DepartmentForm;
import com.hms.gui.DiscountEntryForm;
import com.hms.gui.PatientEntryForm;
import com.hms.gui.TestEntryForm;
import com.hms.gui.UserForm;
import com.hms.gui.ViewPatient;
import com.hms.gui.accounts.DueCollectionForm;
import com.hms.gui.test.DptBiochemistry;
import com.hms.gui.test.DptBlood;
import com.hms.gui.test.DptClinicalPathology;
import com.hms.gui.test.DptClonoscopy;
import com.hms.gui.test.DptColorDoppler;
import com.hms.gui.test.DptCtScan;
import com.hms.gui.test.DptDentalXray;
import com.hms.gui.test.DptDiabetics;
import com.hms.gui.test.DptDuplexStudy;
import com.hms.gui.test.DptECG;
import com.hms.gui.test.DptEEG;
import com.hms.gui.test.DptETT;
import com.hms.gui.test.DptEchocardiogram;
import com.hms.gui.test.DptEndoscopy;
import com.hms.gui.test.DptGastroscopy;
import com.hms.gui.test.DptHaematology;
import com.hms.gui.test.DptHistopathology;
import com.hms.gui.test.DptImmunology;
import com.hms.gui.test.DptMRI;
import com.hms.gui.test.DptMicrobiology;
import com.hms.gui.test.DptPcrLab;
import com.hms.gui.test.DptSonography;
import com.hms.gui.test.DptStool;
import com.hms.gui.test.DptUSG;
import com.hms.gui.test.DptUrine;
import com.hms.gui.test.DptXray;
import com.hms.model.LedgerAC;
import com.hms.model.Patient;
import com.hms.report.controller.PrintReportForm;
import com.hms.report.controller.ReportController;
import com.hms.util.DatePicker;
import com.hms.util.MySession;
import com.hms.util.TheDates;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * @author Alfaz *
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home(String type) {
        initComponents();

        if (type.equals("admin")) {
            menuAccounts.setVisible(true);
        } else if (type.equals("user")) {
            menuAccounts.setVisible(false);
        } else if (type.equals("superadmin")) {
            menuAccounts.setVisible(true);
            menuUserCreate.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem74 = new javax.swing.JMenuItem();
        jMenuItem91 = new javax.swing.JMenuItem();
        jMenuItem112 = new javax.swing.JMenuItem();
        jMenuItem115 = new javax.swing.JMenuItem();
        jMenuItem129 = new javax.swing.JMenuItem();
        jSeparator34 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuSignOut = new javax.swing.JMenuItem();
        jSeparator36 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        menuPatient = new javax.swing.JMenu();
        menuNewPatient = new javax.swing.JMenuItem();
        jSeparator32 = new javax.swing.JPopupMenu.Separator();
        menuViewPatient = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuAllPatient = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuDoctor = new javax.swing.JMenu();
        menuAddDoctor = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        menuDiscount = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuTest = new javax.swing.JMenu();
        menuAddTest = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuTestDepartment = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator35 = new javax.swing.JPopupMenu.Separator();
        menuReport = new javax.swing.JMenu();
        jMenuItem111 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem110 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        menuAccounts = new javax.swing.JMenu();
        menuDueCollection = new javax.swing.JMenuItem();
        jSeparator25 = new javax.swing.JPopupMenu.Separator();
        menuAcStatement = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuMonthly = new javax.swing.JMenuItem();
        jSeparator28 = new javax.swing.JPopupMenu.Separator();
        menuDaily = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        menuCustom = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuAllBillSummery = new javax.swing.JMenuItem();
        menuUserCreate = new javax.swing.JMenu();
        menuCreateUser = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenuItem();

        jMenuItem74.setText("jMenuItem74");

        jMenuItem91.setText("jMenuItem91");

        jMenuItem112.setText("jMenuItem112");

        jMenuItem115.setText("jMenuItem115");

        jMenuItem129.setText("jMenuItem129");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu11.setText("Edit");
        jMenuBar2.add(jMenu11);

        jMenu12.setText("File");
        jMenuBar3.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar3.add(jMenu13);

        jMenu14.setText("File");
        jMenuBar4.add(jMenu14);

        jMenu15.setText("Edit");
        jMenuBar4.add(jMenu15);

        jMenuItem5.setText("jMenuItem5");

        jMenu16.setText("File");
        jMenuBar5.add(jMenu16);

        jMenu17.setText("Edit");
        jMenuBar5.add(jMenu17);

        jMenu18.setText("File");
        jMenuBar6.add(jMenu18);

        jMenu19.setText("Edit");
        jMenuBar6.add(jMenu19);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(150, 30, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));

        jPanel8.setBackground(new java.awt.Color(110, 190, 230));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setFocusCycleRoot(true);

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Hospital Management System");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 255));
        jLabel8.setText("Friends Diagnostic Center");

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Developed By [BU-HiBERNATE]");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Stethoscope.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel9);

        jMenuBar1.setBackground(new java.awt.Color(110, 190, 230));
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));

        menuFile.setForeground(new java.awt.Color(51, 51, 51));
        menuFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/file.png"))); // NOI18N
        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuFile.setIconTextGap(15);
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });
        menuFile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                menuFileKeyReleased(evt);
            }
        });
        menuFile.add(jSeparator3);

        menuSignOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuSignOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        menuSignOut.setText("Log out");
        menuSignOut.setIconTextGap(10);
        menuSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSignOutActionPerformed(evt);
            }
        });
        menuFile.add(menuSignOut);
        menuFile.add(jSeparator36);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
        menuExit.setText("Exit");
        menuExit.setIconTextGap(10);
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        menuPatient.setForeground(new java.awt.Color(51, 51, 51));
        menuPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/patient.png"))); // NOI18N
        menuPatient.setText("Patients");
        menuPatient.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuPatient.setIconTextGap(15);
        menuPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatientActionPerformed(evt);
            }
        });

        menuNewPatient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNewPatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuNewPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/newPatient.PNG"))); // NOI18N
        menuNewPatient.setText("New Patient");
        menuNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewPatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuNewPatient);
        menuPatient.add(jSeparator32);

        menuViewPatient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuViewPatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuViewPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        menuViewPatient.setText("View Patient");
        menuViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewPatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuViewPatient);
        menuPatient.add(jSeparator6);

        menuAllPatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuAllPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ac.png"))); // NOI18N
        menuAllPatient.setText("All Patient Summary");
        menuPatient.add(menuAllPatient);
        menuPatient.add(jSeparator4);

        jMenuBar1.add(menuPatient);
        menuPatient.getAccessibleContext().setAccessibleParent(menuPatient);

        menuDoctor.setForeground(new java.awt.Color(51, 51, 51));
        menuDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/doctor.PNG"))); // NOI18N
        menuDoctor.setText("Doctor");
        menuDoctor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuDoctor.setIconTextGap(15);

        menuAddDoctor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuAddDoctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuAddDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/addDoctor.png"))); // NOI18N
        menuAddDoctor.setText("Add New Doctor");
        menuAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddDoctorActionPerformed(evt);
            }
        });
        menuDoctor.add(menuAddDoctor);
        menuDoctor.add(jSeparator9);

        menuDiscount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuDiscount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuDiscount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/discountDoctor.PNG"))); // NOI18N
        menuDiscount.setText("Discount By");
        menuDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiscountActionPerformed(evt);
            }
        });
        menuDoctor.add(menuDiscount);
        menuDoctor.add(jSeparator2);

        jMenuBar1.add(menuDoctor);

        menuTest.setForeground(new java.awt.Color(51, 51, 51));
        menuTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/test.PNG"))); // NOI18N
        menuTest.setText("Test");
        menuTest.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuTest.setIconTextGap(15);

        menuAddTest.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuAddTest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuAddTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new.png"))); // NOI18N
        menuAddTest.setText("Add New test");
        menuAddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddTestActionPerformed(evt);
            }
        });
        menuTest.add(menuAddTest);
        menuTest.add(jSeparator8);

        menuTestDepartment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        menuTestDepartment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuTestDepartment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new.png"))); // NOI18N
        menuTestDepartment.setText("Add Test Department");
        menuTestDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTestDepartmentActionPerformed(evt);
            }
        });
        menuTest.add(menuTestDepartment);
        menuTest.add(jSeparator1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/viewTest.png"))); // NOI18N
        jMenu1.setText("View Test Report");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Biochemistry");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Blood");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Clinical Pathology");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem6.setText("Colonscopy");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem18.setText("Color Doppler");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem18);

        jMenuItem22.setText("Ct Scan");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem22);

        jMenuItem34.setText("Dental Xray");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem34);

        jMenuItem33.setText("Diabeties");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem33);

        jMenuItem31.setText("Duplex Study");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem31);

        jMenuItem32.setText("ECG");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem32);

        jMenuItem30.setText("EEG");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem30);

        jMenuItem29.setText("ETT");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem29);

        jMenuItem28.setText("Echocardiogram");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem28);

        jMenuItem27.setText("Endoscopy");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem27);

        jMenuItem26.setText("Gastroscopy");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem26);

        jMenuItem24.setText("Heamatology");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem24);

        jMenuItem25.setText("Histopathology");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem25);

        jMenuItem23.setText("Immunology");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem23);

        jMenuItem20.setText("MRI");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem20);

        jMenuItem21.setText("Microbiology");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem21);

        jMenuItem19.setText("PCR Lab");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem19);

        jMenuItem17.setText("Sonography");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem17);

        jMenuItem16.setText("Stool");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        jMenuItem36.setText("USG");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem36);

        jMenuItem35.setText("Urine");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem35);

        jMenuItem4.setText("Xray");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menuTest.add(jMenu1);
        menuTest.add(jSeparator35);

        jMenuBar1.add(menuTest);

        menuReport.setForeground(new java.awt.Color(51, 51, 51));
        menuReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/report.png"))); // NOI18N
        menuReport.setText("Report");
        menuReport.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuReport.setIconTextGap(15);

        jMenuItem111.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem111.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/newPatient.PNG"))); // NOI18N
        jMenuItem111.setText("Patient Test Report");
        jMenuItem111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem111ActionPerformed(evt);
            }
        });
        menuReport.add(jMenuItem111);
        menuReport.add(jSeparator17);

        jMenuItem110.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem110.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/viewTest.png"))); // NOI18N
        jMenuItem110.setText("Patient Report Print");
        jMenuItem110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem110ActionPerformed(evt);
            }
        });
        menuReport.add(jMenuItem110);
        menuReport.add(jSeparator18);

        jMenuBar1.add(menuReport);

        menuAccounts.setForeground(new java.awt.Color(51, 51, 51));
        menuAccounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/account.png"))); // NOI18N
        menuAccounts.setText("Accounts");
        menuAccounts.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuAccounts.setIconTextGap(15);

        menuDueCollection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuDueCollection.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuDueCollection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/due.png"))); // NOI18N
        menuDueCollection.setText("Due Collection");
        menuDueCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDueCollectionActionPerformed(evt);
            }
        });
        menuAccounts.add(menuDueCollection);
        menuAccounts.add(jSeparator25);

        menuAcStatement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuAcStatement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ac.png"))); // NOI18N
        menuAcStatement.setText("AC Statement");
        menuAcStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcStatementActionPerformed(evt);
            }
        });
        menuAccounts.add(menuAcStatement);
        menuAccounts.add(jSeparator7);

        menuMonthly.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuMonthly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/monthly.png"))); // NOI18N
        menuMonthly.setText("Monthly Collection");
        menuMonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMonthlyActionPerformed(evt);
            }
        });
        menuAccounts.add(menuMonthly);
        menuAccounts.add(jSeparator28);

        menuDaily.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuDaily.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/daily.png"))); // NOI18N
        menuDaily.setText("Daily Collection");
        menuDaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDailyActionPerformed(evt);
            }
        });
        menuAccounts.add(menuDaily);
        menuAccounts.add(jSeparator10);

        menuCustom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCustom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/daily.png"))); // NOI18N
        menuCustom.setText("Custom Query");
        menuCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCustomActionPerformed(evt);
            }
        });
        menuAccounts.add(menuCustom);
        menuAccounts.add(jSeparator5);

        menuAllBillSummery.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuAllBillSummery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ac.png"))); // NOI18N
        menuAllBillSummery.setText("All Bill Summery");
        menuAllBillSummery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAllBillSummeryActionPerformed(evt);
            }
        });
        menuAccounts.add(menuAllBillSummery);

        jMenuBar1.add(menuAccounts);

        menuUserCreate.setForeground(new java.awt.Color(51, 51, 51));
        menuUserCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/userCreate.PNG"))); // NOI18N
        menuUserCreate.setText("Create User");
        menuUserCreate.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuUserCreate.setIconTextGap(15);
        menuUserCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserCreateActionPerformed(evt);
            }
        });

        menuCreateUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCreateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        menuCreateUser.setText("Create New User");
        menuCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateUserActionPerformed(evt);
            }
        });
        menuUserCreate.add(menuCreateUser);

        jMenuBar1.add(menuUserCreate);

        menuLogout.setForeground(new java.awt.Color(51, 51, 51));
        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        menuLogout.setText("Log Out");
        menuLogout.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuLogout.setIconTextGap(15);
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });

        menuLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        menuLogOut.setText("Log Out");
        menuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogOutActionPerformed(evt);
            }
        });
        menuLogout.add(menuLogOut);

        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTestDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTestDepartmentActionPerformed
        new DepartmentForm().setVisible(true);
    }//GEN-LAST:event_menuTestDepartmentActionPerformed

    private void menuAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddDoctorActionPerformed
        //new DoctorForm().setVisible(true);
    }//GEN-LAST:event_menuAddDoctorActionPerformed

    private void menuDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiscountActionPerformed
        new DiscountEntryForm().setVisible(true);
    }//GEN-LAST:event_menuDiscountActionPerformed

    private void menuAddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddTestActionPerformed
        new TestEntryForm().setVisible(true);
    }//GEN-LAST:event_menuAddTestActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuFileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuFileKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFileKeyReleased

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        //new BiochemistryTestForm().setVisible(true);
    }//GEN-LAST:event_menuFileActionPerformed

    private void menuUserCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserCreateActionPerformed
        new UserForm().setVisible(true);
    }//GEN-LAST:event_menuUserCreateActionPerformed

    private void menuSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSignOutActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_menuSignOutActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuDailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDailyActionPerformed
        showPaymentStatement("TODAY", new Date(), new Date());
    }//GEN-LAST:event_menuDailyActionPerformed

    private void menuCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateUserActionPerformed
        new UserForm().setVisible(true);
    }//GEN-LAST:event_menuCreateUserActionPerformed

    private void menuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogOutActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_menuLogOutActionPerformed

    private void menuPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatientActionPerformed
        //new PatientEntryForm().setVisible(true);
    }//GEN-LAST:event_menuPatientActionPerformed

    private void menuViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewPatientActionPerformed
        new ViewPatient().setVisible(true);
    }//GEN-LAST:event_menuViewPatientActionPerformed

    private void menuNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewPatientActionPerformed
        new PatientEntryForm().setVisible(true);
    }//GEN-LAST:event_menuNewPatientActionPerformed

    private void menuDueCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDueCollectionActionPerformed
        new DueCollectionForm().setVisible(true);
    }//GEN-LAST:event_menuDueCollectionActionPerformed

    private void menuAcStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcStatementActionPerformed
        String startDate = "2015-01-01";
        String endDate = "2015-12-31";
        showPaymentStatement("All", new TheDates().toDate(startDate), new TheDates().toDate(endDate));

    }//GEN-LAST:event_menuAcStatementActionPerformed

    private void menuMonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMonthlyActionPerformed
        showPaymentStatement("", new TheDates().toDate(new TheDates().getFirstDayOfMonth()), new TheDates().toDate(new TheDates().getLastDayOfMonth()));
    }//GEN-LAST:event_menuMonthlyActionPerformed

    private void menuCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCustomActionPerformed
        DatePicker dp = new DatePicker();
        showPaymentStatement("All", dp.getStartDate(), dp.getEndDate());
    }//GEN-LAST:event_menuCustomActionPerformed

    private void jMenuItem110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem110ActionPerformed
        new PrintReportForm();
    }//GEN-LAST:event_jMenuItem110ActionPerformed

    private void jMenuItem111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem111ActionPerformed
        new ViewPatient().setVisible(true);
    }//GEN-LAST:event_jMenuItem111ActionPerformed

    private void menuAllBillSummeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAllBillSummeryActionPerformed
        DatePicker dp = new DatePicker();
        showPaymentStatement2("All", dp.getStartDate(), dp.getEndDate());
    }//GEN-LAST:event_menuAllBillSummeryActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new DptClonoscopy().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new DptBiochemistry().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new DptBlood().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new DptClinicalPathology().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        new DptColorDoppler().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        new DptCtScan().setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        new DptDentalXray().setVisible(true);
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        new DptDiabetics().setVisible(true);
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        new DptDuplexStudy().setVisible(true);
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        new DptECG().setVisible(true);
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        new DptEEG().setVisible(true);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        new DptETT().setVisible(true);
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        new DptEchocardiogram().setVisible(true);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        new DptEndoscopy().setVisible(true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        new DptGastroscopy().setVisible(true);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        new DptHaematology().setVisible(true);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        new DptHistopathology().setVisible(true);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        new DptImmunology().setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        new DptMRI().setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        new DptMicrobiology().setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        new DptPcrLab().setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        new DptSonography().setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        new DptStool().setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        new DptUSG().setVisible(true);
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        new DptUrine().setVisible(true);
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new DptXray().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public void showPaymentStatement(String findFor, Date start, Date end) {
        Session session = new MySession().getSession();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String startDate = sdf.format(start);
        String endDate = sdf.format(end);

        session.beginTransaction();
        List<LedgerAC> ledgerList = null;
        if (findFor.equals("ALL")) {
            ledgerList = session.createCriteria(LedgerAC.class).list();
        } else {
            String sql = "from  LedgerAC where date >= '" + startDate + "' and  date <= '" + endDate + "' ";
            Query result = session.createQuery(sql);
            ledgerList = result.list();
        }
        session.getTransaction().commit();

        List<Map<String, String>> list = new ArrayList<Map<String, String>>();
        Map<String, String> map2;
        Double amount = 0.0;
        Double total = 0.0;
        for (LedgerAC ac : ledgerList) {
            map2 = new HashMap<String, String>();
            map2.put("receipt", ac.getReceipt());
            map2.put("date", ac.getDate() + "");
            map2.put("amount", ac.getAmount() + "");
            map2.put("patient", ac.getPatient().getRegNo());
            map2.put("total", ac.getPatient().getTotal().toString());
            list.add(map2);
            amount += ac.getAmount();
            total += ac.getPatient().getTotal();
        }

        Map<String, Object> paramMap = new HashMap<String, Object>();
        paramMap.put("start", start + "");
        paramMap.put("end", end + "");
        paramMap.put("amount", amount + "");
        paramMap.put("total", total + "");

        new ReportController().showReport("stm", paramMap, list);
    }

    public void showPaymentStatement2(String findFor, Date start, Date end) {
        Session session = new MySession().getSession();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        String sql;
        session.beginTransaction();
        if (start == null || end == null) {
            sql = "from  Patient";
        } else {
            String startDate = sdf.format(start);
            String endDate = sdf.format(end);
            sql = "from  Patient where regDate >= '" + startDate + "' and  regDate <= '" + endDate + "' ";
        }
        Query result = session.createQuery(sql);
        List<Patient> patientList = result.list();
        session.getTransaction().commit();

        List<Map<String, String>> list = new ArrayList<Map<String, String>>();
        Map<String, String> map2;
        Double total = 0.0;
        Double discount = 0.0;
        Double paid = 0.0;
        Double due = 0.0;
        for (Patient patient : patientList) {
            map2 = new HashMap<String, String>();
            map2.put("regNo", patient.getRegNo());
            map2.put("date", patient.getRegDate() + "");
            map2.put("name", patient.getPatientName());
            map2.put("total", patient.getTotal().toString());
            map2.put("discount", patient.getDiscount() + "");
            map2.put("paid", patient.getPaid() + "");
            map2.put("due", patient.getDue() + "");
            list.add(map2);

            total += patient.getTotal();
            discount += patient.getDiscount();
            paid += patient.getPaid();
            due += patient.getDue();
        }
        Map<String, Object> paramMap = new HashMap<String, Object>();
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MM-yyyy");
        String a = "";
        String b = "";
        if (start == null || end == null) {
            a = "";
            b = "";
            paramMap.put("date", "");
        } else {
            a = sdf2.format(start);
            b = sdf2.format(end);
            paramMap.put("date", a + " to " + b);
        }

        //paramMap.put("amount", amount + "");
        paramMap.put("total", total + "");
        paramMap.put("discount", discount + "");
        paramMap.put("paid", paid + "");
        paramMap.put("due", due + "");

        new ReportController().showReport("stm2", paramMap, list);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home("superadmin").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem110;
    private javax.swing.JMenuItem jMenuItem111;
    private javax.swing.JMenuItem jMenuItem112;
    private javax.swing.JMenuItem jMenuItem115;
    private javax.swing.JMenuItem jMenuItem129;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem91;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator25;
    private javax.swing.JPopupMenu.Separator jSeparator28;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator32;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JPopupMenu.Separator jSeparator35;
    private javax.swing.JPopupMenu.Separator jSeparator36;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem menuAcStatement;
    private javax.swing.JMenu menuAccounts;
    private javax.swing.JMenuItem menuAddDoctor;
    private javax.swing.JMenuItem menuAddTest;
    private javax.swing.JMenuItem menuAllBillSummery;
    private javax.swing.JMenuItem menuAllPatient;
    private javax.swing.JMenuItem menuCreateUser;
    private javax.swing.JMenuItem menuCustom;
    private javax.swing.JMenuItem menuDaily;
    private javax.swing.JMenuItem menuDiscount;
    private javax.swing.JMenu menuDoctor;
    private javax.swing.JMenuItem menuDueCollection;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuLogOut;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenuItem menuMonthly;
    private javax.swing.JMenuItem menuNewPatient;
    private javax.swing.JMenu menuPatient;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem menuSignOut;
    private javax.swing.JMenu menuTest;
    private javax.swing.JMenuItem menuTestDepartment;
    private javax.swing.JMenu menuUserCreate;
    private javax.swing.JMenuItem menuViewPatient;
    // End of variables declaration//GEN-END:variables
}
